/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controllers.DilosiMathimatwnCON;
import Controllers.InsertGradesFromTeacherCON;
import Model.Athina;
import Model.Student;
import Model.Teacher;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;




public class MainMenu extends javax.swing.JFrame {

    private Athina university;
    
    
    public MainMenu() {
        initComponents();
        university = new Athina();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        insertStudentBtn = new javax.swing.JButton();
        InsertGrammateiaBtn = new javax.swing.JButton();
        insertTeacherBtn = new javax.swing.JButton();
        passwordInput = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ΑΘΗΝΑ");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Uername :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password :");

        usernameInput.setText(" ");

        insertStudentBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertStudentBtn.setText("Εισοδος Φοιτητη");
        insertStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertStudentBtnActionPerformed(evt);
            }
        });

        InsertGrammateiaBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        InsertGrammateiaBtn.setText("Γραμματεια");
        InsertGrammateiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertGrammateiaBtnActionPerformed(evt);
            }
        });

        insertTeacherBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertTeacherBtn.setText("Εισοδος Καθηγητη");
        insertTeacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertTeacherBtnActionPerformed(evt);
            }
        });

        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("des kwdiko");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertStudentBtn)
                .addGap(45, 45, 45)
                .addComponent(insertTeacherBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(InsertGrammateiaBtn)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertStudentBtn)
                    .addComponent(insertTeacherBtn)
                    .addComponent(InsertGrammateiaBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(msg))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void insertStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertStudentBtnActionPerformed
        //Παίρνουμε το username και το password του χρήστη
        String usernameIn = usernameInput.getText();
        String passwordIn = passwordInput.getText();
        System.out.println("PasswordIN " + passwordIn);
        //Παίρνουμε την λίστα με τους φοιτητές
        ArrayList<Student> students = university.getStudents();
        
        String password = "";
        Student authorizedStudent = null;
        boolean found = false;
        //Βρίσκουμε τον φοιτητή με το συγκεκριμένο username
        //και παίρνουμε το password που του έχει δοθεί από τη γραμματεία
        for(Student student:students){;
            if(student.getUsername().equals(usernameIn)){
                password = student.getPassword();
                authorizedStudent = student;
                found = true;
                System.out.println("Student found");
                System.out.println("Student password " +password);
                break;
            }
        }
        if(found){//Εάν βρεθεί το username
            //Εάν το password είναι σωστό
            if (passwordIn.equals(password)){
                //Καθαρισμός παιδίων φόρμας
                usernameInput.setText(null);
                passwordInput.setText(null);

                DilosiMathimatwnCON enroll = new DilosiMathimatwnCON(university, authorizedStudent);
                msg.setText("");
            }
            else{//Λάθος password
                JOptionPane.showMessageDialog(null, "Wrond  Passwrod please try again", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }else{//To username δεν βρέθηκε
            JOptionPane.showMessageDialog(null, "Username don't found. Please try again", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_insertStudentBtnActionPerformed

    private void insertTeacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertTeacherBtnActionPerformed
        String usernameIn = usernameInput.getText();
        String passwordIn = passwordInput.getText();
        
        ArrayList<Teacher> teachers = university.getTeachers();
        
        String password = "";
        Teacher authorizedTeacher = null;
        boolean found = false;
        //Βρίσκουμε τον καθηγητη με το συγκεκριμένο username
        //και παίρνουμε το password που του έχει δοθεί από τη γραμματεία
        for(Teacher teacher:teachers){;
            if(teacher.getUsername().equals(usernameIn)){
                password = teacher.getPassword();
                authorizedTeacher = teacher;
                found = true;
                System.out.println("Teacher found");
                System.out.println("Teacher password " + password);
                break;
            }
        }
        if(found)//Αν βρεθεί ο χρήστης
            //Εάν το password είναι σωστό
        if (passwordIn.equals(password)){
            //Καθαρισμός παιδίων φόρμας
            usernameInput.setText(null);
            passwordInput.setText(null);

            new InsertGradesFromTeacherCON(university, authorizedTeacher);
            msg.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrond  Passwrod please try again", "Error", JOptionPane.ERROR_MESSAGE);

        }
        else{
            JOptionPane.showMessageDialog(null, "Username don't found. Please try again", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
       
    }//GEN-LAST:event_insertTeacherBtnActionPerformed

    private void InsertGrammateiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertGrammateiaBtnActionPerformed
        //Παίρνουμε το username και το password
        String username = usernameInput.getText();
        String password = passwordInput.getText();
        
        //Ελέγχουμε την είσοδο
        if (password.contains("studin")&& (username.contains("studin"))){
            usernameInput.setText(null);
            passwordInput.setText(null);
            //systemExit();
            //Δημιουργία του μενου επιλογών της γραμματείας
            new GrammateiaActionsUI(university).setVisible(true);
            //Αν είναι σωστή τότε δημιουργούμε έναν Controller
            
            //Καθαρίζουμε τα inputs
            msg.setText("");
        }
        else{//Σε περίπτωση λάθους εμφανίζεται το ακόλουθο μήνυμα
            JOptionPane.showMessageDialog(null, "Wrong username or password. Please try again", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_InsertGrammateiaBtnActionPerformed
 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        stoixeisLogin info = new stoixeisLogin();
        info.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertGrammateiaBtn;
    private javax.swing.JButton insertStudentBtn;
    private javax.swing.JButton insertTeacherBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msg;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables

private void systemExit(){
    WindowEvent winCloseing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
}

}
